# Generated by Django 4.2 on 2023-04-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.CharField(blank=True, max_length=10000000000, null=True, verbose_name='Лицо'),
        ),
    ]
