# Generated by Django 4.2 on 2023-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='face_of_user/%Y/%m/%d/', verbose_name='Лицо'),
        ),
    ]
