# Generated by Django 4.2 on 2023-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_alter_user_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_false',
            field=models.BooleanField(default=True, verbose_name='Хэш предыдущего блока'),
        ),
    ]
