# Generated by Django 4.2 on 2023-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_alter_user_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birthday',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телфона'),
        ),
    ]
