# Generated by Django 4.1.3 on 2023-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_alter_user_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perv_hash',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Хэш предыдущего блока'),
        ),
    ]
