# Generated by Django 4.1.3 on 2023-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0005_user_temporary_field_key_aes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birthday',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дата рождения'),
        ),
    ]
