# Generated by Django 4.1.3 on 2023-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0006_alter_user_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телфона'),
        ),
    ]
