# Generated by Django 4.1.3 on 2023-04-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0007_alter_user_number_of_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='perv_hash',
            new_name='_hash',
        ),
    ]
