# Generated by Django 4.1.3 on 2023-04-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0008_rename_perv_hash_user__hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temporary_field_key_aes',
        ),
    ]
